[package]
name = "compet_easy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = {version = "0.11", features = ["blocking", "rustls-tls-webpki-roots"]}
scraper = "0.13.0"
